type Order {
  place: String!
  date: String!
  user: String!
  food: String!
}

type Query {
  hello: String!
  orders: [Order!]!
}

type Mutation {
  orderFood(date: String!, food: String!): Boolean!
  cancelFoodOrder(date: String!): Boolean!
}

schema {
  query: Query
  mutation: Mutation
}
